source:
  host: 192.168.109.12
  port: 5432
  username: openerp
  password: A6eC9qf0AenECZdh
  database: Portal_prod
  batch: 100000
destination:
  ssh:
    host: 192.168.109.17
    user: delmar
    pkey: /conf/delmar_aws_key.pem
    password: XCVawt766!
  db:
    user: odoo
    password: odoo
    database: delta-feature-data-bkp
    schema: public

#  ssh_private_key=base_dir + cfg['destination']['ssh']['pkey']